[changes]
releases_directory = "docs/releases"
[changes.labels.docs]
id = 153027109
url = "https://api.github.com/repos/michaeljoseph/changes/labels/docs"
name = "docs"
color = "0052cc"
default = false
description = "Docs"
[changes.labels.bug]
id = 52048163
url = "https://api.github.com/repos/michaeljoseph/changes/labels/bug"
name = "bug"
color = "fc2929"
default = true
description = "Bugs"
[changes.labels.enhancement]
id = 52048165
url = "https://api.github.com/repos/michaeljoseph/changes/labels/enhancement"
name = "enhancement"
color = "84b6eb"
default = true
description = "Enhancements"
[changes.labels.chore]
id = 721722843
url = "https://api.github.com/repos/michaeljoseph/changes/labels/chore"
name = "chore"
color = "5319e7"
default = false
description = "Chores"
