checks:
    python:
        code_rating: true
        duplicate_code: true
        format_bad_indentation:
            indentation: '4 spaces'
        format_mixed_indentation: true
        format_line_too_long:
            max_length: '79'
        imports_relative_import: true
        imports_wildcard_import: true
        format_bad_whitespace: true
        format_multiple_statements: true
        basic_invalid_name:
            functions: '[a-z_][a-z0-9_]{2,30}$'
            variables: '[a-z_][a-z0-9_]{2,30}$'
            whitelisted_names: 'i,j,k,ex,Run,_'
            constants: '(([A-Z_][A-Z0-9_]*)|(__.*__))$'
            attributes: '[a-z_][a-z0-9_]{2,30}$'
            arguments: '[a-z_][a-z0-9_]{2,30}$'
            class_attributes: '([A-Za-z_][A-Za-z0-9_]{2,30}|(__.*__))$'
            inline_vars: '[A-Za-z_][A-Za-z0-9_]*$'
            classes: '[A-Z_][a-zA-Z0-9]+$'
            modules: '(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+))$'
            methods: '[a-z_][a-z0-9_]{2,30}$'
        classes_no_self_argument: true
        classes_bad_mcs_method_argument: true
        classes_bad_classmethod_argument: true
        variables_used_before_assignment: true
        variables_unpacking_non_sequence: true
        variables_undefined_variable: true
        variables_undefined_loop_variable: true
        variables_undefined_all_variable: true
        variables_redefine_in_handler: true
        variables_no_name_in_module: true
        variables_global_variable_undefined: true
        variables_redefined_outer_name: true
        typecheck_not_callable: true
        variables_unbalanced_tuple_unpacking: true
        typecheck_unexpected_keyword_arg: true
        typecheck_no_value_for_parameter: true
        typecheck_no_member: true
        typecheck_missing_kwoa: true
        typecheck_maybe_no_member: true
        typecheck_duplicate_keyword_arg: true
        typecheck_too_many_function_args: true
        typecheck_assignment_from_none: true
        typecheck_assignment_from_no_return: true
        typecheck_redundant_keyword_arg: true
        string_unused_format_string_key: true
        string_truncated_format_string: true
        string_too_many_format_args: true
        string_too_few_format_args: true
        string_mixed_format_string: true
        string_missing_format_string_key: true
        string_format_needs_mapping: true
        string_constant_anomalous_unicode_escape_in_string: true
        string_constant_anomalous_backslash_in_string: true
        string_bad_str_strip_call: true
        string_bad_format_string_key: true
        open_mode_bad_open_mode: true
        string_bad_format_character: true
        logging_unsupported_format: true
        logging_too_few_args: true
        logging_too_many_args: true
        logging_format_truncated: true
        imports_reimported: true
        imports_import_self: true
        exceptions_raising_string: true
        exceptions_raising_non_exception: true
        imports_import_error: true
        exceptions_raising_bad_type: true
        exceptions_notimplemented_raised: true
        exceptions_catching_non_exception: true
        exceptions_bad_except_order: true
        classes_valid_slots: true
        classes_signature_differs: true
        classes_non_iterator_returned: true
        classes_no_method_argument: true
        classes_missing_interface_method: true
        classes_interface_is_not_class: true
        classes_arguments_differ: true
        classes_access_member_before_definition: true
        classes_abstract_method: true
        basic_yield_outside_function: true
        basic_not_in_loop: true
        basic_nonexistent_operator: true
        basic_missing_reversed_argument: true
        basic_missing_module_attribute: true
        basic_lost_exception: true
        basic_duplicate_argument_name: true
        basic_bad_reversed_sequence: true
        basic_assert_on_tuple: true
        basic_abstract_class_instantiated: true
        variables_invalid_all_object: true
        imports_cyclic_import: true
        classes_bad_staticmethod_argument: true
        classes_bad_context_manager: true
        basic_return_outside_function: true
        basic_return_in_init: true
        basic_return_arg_in_generator: true
        basic_init_is_generator: true
        basic_duplicate_key: true

filter:
    excluded_paths:
        - '*/test/*'

tools:
    external_code_coverage:
        runs: 3
