environment:
  matrix:
    - PYTHON: "C:\\Python35"
      TOX_ENV: "py35"


init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install -r requirements.txt"

build: false

test_script:
  - "%PYTHON%/Scripts/pytest"

after_test:
  - "%PYTHON%/Scripts/coverage combine"
  - "%PYTHON%/Scripts/codecov"
