version: 2
jobs:
  build:
    working_directory: ~/changes
    docker:
      - image: circleci/python:3.7.9
    steps:
    - checkout
    - restore_cache:  # ensure this step occurs *before* installing dependencies
        key: deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
    - run: sudo pip install --upgrade tox pip wheel
    - run: tox
    - save_cache:
        key: deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
        paths:
          - ".tox"