# https://circleci.com/developer/orbs/orb/circleci/python
version: 2.1
orbs:
  python: circleci/python@1.4.0
jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: tox
workflows:
  main:
    jobs:
      - test