name: Continuous Integration
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.7"
      - name: "Pre-commit linting"
        run: |
          python -m pip install --upgrade pip tox
          tox -e lint

  test:
    name: "Tests ${{ matrix.python-version }} on ${{ matrix.platform }}"
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Run tests with Python ${{ matrix.python-version }} on ${{ matrix.platform }}"
        env:
          PLATFORM: ${{ matrix.platform }}
        run: |
          python -m pip install --upgrade pip tox tox-gh-actions
          tox

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ matrix.python-version }}-${{ matrix.platform }}
          path: |
            test-reports/junit.xml
            test-reports/cobertura.xml
        if: ${{ always() }}
